### ISSUE TITLE
Choice of a language on top

### ISSUE THREAD

**Issue by Saaaam** [qTox/qTox-Website#2]
Hello,

Currently, the choice of the language on the website can be done at the bottom of the page. But when a non-English person comes for the first time, the only thing that person can see is a language he/she doesn't understand.
A little improvement would be to add the choice of the language at the top, like at the right of the items of the navigation bar. A flag + 2 letters is a good solution to make people understand they have to click there to change the language. Here is an example of what I have in mind:

![screenshot_qtox_lang](https://cloud.githubusercontent.com/assets/19937009/16061463/5524fe8a-328d-11e6-9e98-18288a0dd0d9.jpg)

(Don't pay attention to the fact that my version of the website is in French while I put an American flag… >.< personal mistake)

**Comment by Saaaam** [comment]
By the way, if this proposal is accepted, I can try to code it by myself…

**Comment by zetok** [comment]
Note that only stuff that github pages currently support can be used on the website: https://pages.github.com/
