### ISSUE TITLE
Qtox crashes home wifi, but only on specific laptop

### ISSUE THREAD

**Issue by throwaway234q23414542523456465** [qTox/qTox-Website#28]
I have no idea why or how this makes sense, but when I use qtox on my home wifi it makes it so that no device can connect to the internet, including my laptop. When I attempt to use qtox on another (university network) it just fails to connect entirely, but my computer can still access the internet and nobody else's ability to connect is affected. On both my home network and my university network I've been able to run qtox on my windows 7 desktop without a snag. My laptop is running windows 10.

**Comment by zetok** [comment]
https://github.com/qTox/qTox/wiki/FAQ#why-is-qtox-killing-my-internet-connection
